# Module: Pandas Assignments
## Lesson: Pandas


### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.
2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.
2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.
2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.
2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [1]:
import numpy as np 
import pandas as pd
data = np.random.randint(1,101,size=(6,4))
print(data)
pd_data = pd.DataFrame(data=data,columns=["A","B","C","D"])
pd_data
pd_data.set_index("A", inplace=True)
pd_data

[[27 34 90 65]
 [49 54 15 26]
 [12 28 77 14]
 [12 85 96 14]
 [68 53 25 22]
 [ 9 52  8 35]]

     B   C   D
A
27  34  90  65
49  54  15  26
12  28  77  14
12  85  96  14
68  53  25  22
9   52   8  35

2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [2]:
data = np.random.randint(1,101,size=(3,3))
df = pd.DataFrame(data=data,columns=["A","B","C"],index=("X","Y","Z"))
print(df)
print(df["B"]["Y"])

    A   B   C
X  22   6  23
Y  36  28  38
Z  51  72  22
28

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [4]:
df = pd.DataFrame(np.random.randint(1,100,size=(5,3)),columns=["A","B","C"],index=("V","W","X","Y","Z"))
display(df)
df["product"] = df["A"]*df["B"]
display(df)

    A   B   C
V  47  44  54
W  31  10  37
X  29  60  92
Y  30  67  23
Z  44  74  56

    A   B   C  product
V  47  44  54     2068
W  31  10  37      310
X  29  60  92     1740
Y  30  67  23     2010
Z  44  74  56     3256

2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [5]:
df = pd.DataFrame(np.random.randint(1,100, size=(4,3)),columns=["A","B","C"])
display(df)
row_sum = df.sum(axis=1)
col_sum = df.sum(axis=0)
display(row_sum)
display(col_sum)

    A   B   C
0  36  84   5
1  12  67  77
2  15  77  58
3  67  49  64

0    125
1    156
2    150
3    180
dtype: int64

A    130
B    277
C    204
dtype: int64

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [7]:
df = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:")
display(df)

df.iloc[0, 1] = np.nan
df.iloc[2, 2] = np.nan
df.iloc[4, 0] = np.nan
print("DataFrame with NaN values:")
display(df)

df.fillna(df.mean(), inplace=True)
print("DataFrame with NaN values filled:")
display(df)

Original DataFrame:

    A   B   C
0  58  79  14
1   7  20  96
2  84  65  33
3  32   3  97
4  83  82  83

DataFrame with NaN values:

      A     B     C
0  58.0   NaN  14.0
1   7.0  20.0  96.0
2  84.0  65.0   NaN
3  32.0   3.0  97.0
4   NaN  82.0  83.0

DataFrame with NaN values filled:

       A     B     C
0  58.00  42.5  14.0
1   7.00  20.0  96.0
2  84.00  65.0  72.5
3  32.00   3.0  97.0
4  45.25  82.0  83.0

2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [10]:
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 4)), columns=['A', 'B', 'C', 'D'])
print("Original DataFrame:")
display(df)
df.iloc[1, 2] = np.nan
df.iloc[3, 0] = np.nan
df.iloc[5, 1] = np.nan
print("DataFrame with NaN values:")
display(df)
df.dropna(inplace=True)
print("DataFrame with NaN values dropped:")
display(df)

Original DataFrame:

    A   B   C   D
0  79  22  15  34
1   1  87  83  23
2  65  25  66  53
3  70  66  83  17
4  97  75  79  15
5  76  81  15  90

DataFrame with NaN values:

      A     B     C   D
0  79.0  22.0  15.0  34
1   1.0  87.0   NaN  23
2  65.0  25.0  66.0  53
3   NaN  66.0  83.0  17
4  97.0  75.0  79.0  15
5  76.0   NaN  15.0  90

DataFrame with NaN values dropped:

      A     B     C   D
0  79.0  22.0  15.0  34
2  65.0  25.0  66.0  53
4  97.0  75.0  79.0  15

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [21]:
df = pd.DataFrame({'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Value': np.random.randint(1, 100, size=10)})
print("Original DataFrame:")
display(df)

query = df.groupby("Category")["Value"].agg(["sum","mean"])
display(query)

Original DataFrame:

  Category  Value
0        A     69
1        A     80
2        A     61
3        A     91
4        C     16
5        A     83
6        B     51
7        B      7
8        C     70
9        A     41

          sum       mean
Category
A         425  70.833333
B          58  29.000000
C          86  43.000000

2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [20]:
df = pd.DataFrame({'Product': np.random.choice(['Prod1', 'Prod2', 'Prod3'], size=10), 'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Sales': np.random.randint(1, 100, size=10)})
print("Original DataFrame:")
display(df)
query = df.groupby("Category")["Sales"].sum()
display(query)

Original DataFrame:

  Product Category  Sales
0   Prod3        B     28
1   Prod2        B     19
2   Prod2        A     58
3   Prod3        A     29
4   Prod2        B     61
5   Prod2        B     21
6   Prod3        A     89
7   Prod3        B     31
8   Prod1        C     85
9   Prod3        B     41

Category
A    176
B    201
C     85
Name: Sales, dtype: int32

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [24]:
df1 = pd.DataFrame({'Key': ['A', 'B', 'C', 'D'], 'Value1': np.random.randint(1, 100, size=4)})
df2 = pd.DataFrame({'Key': ['A', 'B', 'C', 'E'], 'Value2': np.random.randint(1, 100, size=4)})
print("DataFrame 1:")
display(df1)
display(df2)
df1.merge(df2, how="outer",on="Key")

DataFrame 1:

  Key  Value1
0   A      10
1   B      13
2   C      37
3   D      37

  Key  Value2
0   A      73
1   B      48
2   C      31
3   E      46

  Key  Value1  Value2
0   A    10.0    73.0
1   B    13.0    48.0
2   C    37.0    31.0
3   D    37.0     NaN
4   E     NaN    46.0

2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns

In [26]:
df1 = pd.DataFrame({'A': np.random.randint(1, 100, size=3), 'B': np.random.randint(1, 100, size=3)})
df2 = pd.DataFrame({'C': np.random.randint(1, 100, size=3), 'D': np.random.randint(1, 100, size=3)})
print("DataFrame 1:")
display(df1)
print("DataFrame 2:")
display(df2)

# Concatenate the DataFrames along the rows
concat_rows = pd.concat([df1, df2], axis=0)
print("Concatenated DataFrame (rows):")
display(concat_rows)

# Concatenate the DataFrames along the columns
concat_columns = pd.concat([df1, df2], axis=1)
print("Concatenated DataFrame (columns):")
display(concat_columns)

DataFrame 1:

    A   B
0  62  60
1  86  51
2   1  96

DataFrame 2:

    C   D
0  35  32
1   7  95
2   1   5

Concatenated DataFrame (rows):

      A     B     C     D
0  62.0  60.0   NaN   NaN
1  86.0  51.0   NaN   NaN
2   1.0  96.0   NaN   NaN
0   NaN   NaN  35.0  32.0
1   NaN   NaN   7.0  95.0
2   NaN   NaN   1.0   5.0

Concatenated DataFrame (columns):

    A   B   C   D
0  62  60  35  32
1  86  51   7  95
2   1  96   1   5