# 🐼 Pandas Assignments

## 📖 Overview

This notebook contains my solutions to the Pandas assignments completed as part of my Data Analytics learning journey.

These assignments cover the core concepts required for data analysis using Pandas, including DataFrame operations, indexing, aggregation, time series analysis, pivot tables, and text processing.

---

## 📚 Topics Covered

- ✅ DataFrame Creation
- ✅ Indexing (`loc` & `iloc`)
- ✅ DataFrame Operations
- ✅ Missing Value Handling
- ✅ Aggregation & GroupBy
- ✅ Merge & Concatenation
- ✅ Time Series Analysis
- ✅ MultiIndex DataFrames
- ✅ Pivot Tables
- ✅ Applying Functions (`apply`, `lambda`)
- ✅ Working with Text Data

---

## 🛠 Technologies Used

- Python
- NumPy
- Pandas
- Jupyter Notebook

---

## 🎯 Goal

The objective of these assignments is to strengthen my understanding of Pandas and prepare for real-world Data Analysis, Exploratory Data Analysis (EDA), and Machine Learning workflows.

### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [1]:
import numpy as np 
import pandas as pd
data = np.random.randint(1,101,size=(6,4))
print(data)
pd_data = pd.DataFrame(data=data,columns=["A","B","C","D"])
pd_data
pd_data.set_index("A", inplace=True)
pd_data

[[84  5 84 35]
 [27 31 35 28]
 [29  7 35  8]
 [80  4 21 60]
 [57 74 69 82]
 [55 64 53  8]]

     B   C   D
A
84   5  84  35
27  31  35  28
29   7  35   8
80   4  21  60
57  74  69  82
55  64  53   8

2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [2]:
data = np.random.randint(1,101,size=(3,3))
df = pd.DataFrame(data=data,columns=["A","B","C"],index=("X","Y","Z"))
print(df)
print(df["B"]["Y"])

    A   B   C
X  96  34  17
Y  46  70  90
Z  50  61  22
70

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [3]:
df = pd.DataFrame(np.random.randint(1,100,size=(5,3)),columns=["A","B","C"],index=("V","W","X","Y","Z"))
display(df)
df["product"] = df["A"]*df["B"]
display(df)

    A   B   C
V  52  57  84
W  65  14   8
X  43  46  39
Y  50  36   9
Z  94  11   1

    A   B   C  product
V  52  57  84     2964
W  65  14   8      910
X  43  46  39     1978
Y  50  36   9     1800
Z  94  11   1     1034

2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [4]:
df = pd.DataFrame(np.random.randint(1,100, size=(4,3)),columns=["A","B","C"])
display(df)
row_sum = df.sum(axis=1)
col_sum = df.sum(axis=0)
display(row_sum)
display(col_sum)

    A   B   C
0  38  76  54
1  86  75  25
2  91  24  68
3  93  21  96

0    168
1    186
2    183
3    210
dtype: int64

A    308
B    196
C    243
dtype: int64

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [5]:
df = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:")
display(df)

df.iloc[0, 1] = np.nan
df.iloc[2, 2] = np.nan
df.iloc[4, 0] = np.nan
print("DataFrame with NaN values:")
display(df)

df.fillna(df.mean(), inplace=True)
print("DataFrame with NaN values filled:")
display(df)

Original DataFrame:

    A   B   C
0  28  40  79
1  42  52  11
2  31  67  13
3  28  58  47
4  80  50  41

DataFrame with NaN values:

      A     B     C
0  28.0   NaN  79.0
1  42.0  52.0  11.0
2  31.0  67.0   NaN
3  28.0  58.0  47.0
4   NaN  50.0  41.0

DataFrame with NaN values filled:

       A      B     C
0  28.00  56.75  79.0
1  42.00  52.00  11.0
2  31.00  67.00  44.5
3  28.00  58.00  47.0
4  32.25  50.00  41.0

2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [6]:
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 4)), columns=['A', 'B', 'C', 'D'])
print("Original DataFrame:")
display(df)
df.iloc[1, 2] = np.nan
df.iloc[3, 0] = np.nan
df.iloc[5, 1] = np.nan
print("DataFrame with NaN values:")
display(df)
df.dropna(inplace=True)
print("DataFrame with NaN values dropped:")
display(df)

Original DataFrame:

    A   B   C   D
0  52  46  92  36
1  90  75  63  70
2  55  42  12  80
3  91  97  15  40
4  10  32  87  71
5  75  75  84  76

DataFrame with NaN values:

      A     B     C   D
0  52.0  46.0  92.0  36
1  90.0  75.0   NaN  70
2  55.0  42.0  12.0  80
3   NaN  97.0  15.0  40
4  10.0  32.0  87.0  71
5  75.0   NaN  84.0  76

DataFrame with NaN values dropped:

      A     B     C   D
0  52.0  46.0  92.0  36
2  55.0  42.0  12.0  80
4  10.0  32.0  87.0  71

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [7]:
df = pd.DataFrame({'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Value': np.random.randint(1, 100, size=10)})
print("Original DataFrame:")
display(df)

query = df.groupby("Category")["Value"].agg(["sum","mean"])
display(query)

Original DataFrame:

  Category  Value
0        C     29
1        B     87
2        A      7
3        B      9
4        A     12
5        B     60
6        A     65
7        C     95
8        B     53
9        C      5

          sum   mean
Category
A          84  28.00
B         209  52.25
C         129  43.00

2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [8]:
df = pd.DataFrame({'Product': np.random.choice(['Prod1', 'Prod2', 'Prod3'], size=10), 'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Sales': np.random.randint(1, 100, size=10)})
print("Original DataFrame:")
display(df)
query = df.groupby("Category")["Sales"].sum()
display(query)

Original DataFrame:

  Product Category  Sales
0   Prod2        A     10
1   Prod1        A     74
2   Prod2        C     35
3   Prod3        B     92
4   Prod2        C     57
5   Prod3        A      2
6   Prod2        A     18
7   Prod1        B      8
8   Prod1        A     81
9   Prod2        A     22

Category
A    207
B    100
C     92
Name: Sales, dtype: int32

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [9]:
df1 = pd.DataFrame({'Key': ['A', 'B', 'C', 'D'], 'Value1': np.random.randint(1, 100, size=4)})
df2 = pd.DataFrame({'Key': ['A', 'B', 'C', 'E'], 'Value2': np.random.randint(1, 100, size=4)})
print("DataFrame 1:")
display(df1)
display(df2)
df1.merge(df2, how="outer",on="Key")

DataFrame 1:

  Key  Value1
0   A      49
1   B      52
2   C      39
3   D      98

  Key  Value2
0   A      84
1   B      95
2   C      99
3   E      37

  Key  Value1  Value2
0   A    49.0    84.0
1   B    52.0    95.0
2   C    39.0    99.0
3   D    98.0     NaN
4   E     NaN    37.0

2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns

In [10]:
df1 = pd.DataFrame({'A': np.random.randint(1, 100, size=3), 'B': np.random.randint(1, 100, size=3)})
df2 = pd.DataFrame({'C': np.random.randint(1, 100, size=3), 'D': np.random.randint(1, 100, size=3)})
print("DataFrame 1:")
display(df1)
print("DataFrame 2:")
display(df2)

# Concatenate the DataFrames along the rows
concat_rows = pd.concat([df1, df2], axis=0)
print("Concatenated DataFrame (rows):")
display(concat_rows)

# Concatenate the DataFrames along the columns
concat_columns = pd.concat([df1, df2], axis=1)
print("Concatenated DataFrame (columns):")
display(concat_columns)

DataFrame 1:

    A   B
0  43  82
1  82  36
2  95  48

DataFrame 2:

    C   D
0  76  79
1  87  12
2  70  13

Concatenated DataFrame (rows):

      A     B     C     D
0  43.0  82.0   NaN   NaN
1  82.0  36.0   NaN   NaN
2  95.0  48.0   NaN   NaN
0   NaN   NaN  76.0  79.0
1   NaN   NaN  87.0  12.0
2   NaN   NaN  70.0  13.0

Concatenated DataFrame (columns):

    A   B   C   D
0  43  82  76  79
1  82  36  87  12
2  95  48  70  13

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

In [13]:
date_rng = pd.date_range(start='2025-01-01', end='2025-12-31', freq='D')
df = pd.DataFrame(date_rng, columns=['date'])
df['data'] = np.random.randint(0, 100, size=(len(date_rng)))
df.set_index('date', inplace=True)
print("Original DataFrame:")
display(df)

monthly_mean = df.resample('ME').mean()
print("Monthly mean DataFrame:")
display(monthly_mean)

Original DataFrame:

            data
date
2025-01-01    90
2025-01-02    64
2025-01-03    42
2025-01-04    11
2025-01-05    16
...          ...
2025-12-27    79
2025-12-28    50
2025-12-29    38
2025-12-30    31
2025-12-31    76

[365 rows x 1 columns]

Monthly mean DataFrame:

                 data
date
2025-01-31  53.838710
2025-02-28  47.607143
2025-03-31  46.096774
2025-04-30  56.200000
2025-05-31  51.677419
2025-06-30  48.900000
2025-07-31  44.870968
2025-08-31  46.774194
2025-09-30  51.700000
2025-10-31  57.903226
2025-11-30  51.166667
2025-12-31  52.290323

2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

In [15]:
date_rng = pd.date_range(start='2025-01-01', end='2025-12-31', freq='D')
df = pd.DataFrame(date_rng, columns=['date'])
df['data'] = np.random.randint(0, 100, size=(len(date_rng)))
df.set_index('date', inplace=True)
print("Original DataFrame:")
display(df)

rolling_mean = df.rolling(window=7).mean()
print("Rolling mean DataFrame:")
display(rolling_mean.head(20))

Original DataFrame:

            data
date
2025-01-01    25
2025-01-02    45
2025-01-03    11
2025-01-04    86
2025-01-05    91
...          ...
2025-12-27    66
2025-12-28    95
2025-12-29    42
2025-12-30    54
2025-12-31    61

[365 rows x 1 columns]

Rolling mean DataFrame:

                 data
date
2025-01-01        NaN
2025-01-02        NaN
2025-01-03        NaN
2025-01-04        NaN
2025-01-05        NaN
2025-01-06        NaN
2025-01-07  54.000000
2025-01-08  58.142857
2025-01-09  62.142857
2025-01-10  70.285714
2025-01-11  66.571429
2025-01-12  64.428571
2025-01-13  67.857143
2025-01-14  63.714286
2025-01-15  60.714286
2025-01-16  58.571429
2025-01-17  61.142857
2025-01-18  59.000000
2025-01-19  52.000000
2025-01-20  52.571429

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.

In [17]:
# Create a Pandas DataFrame with a MultiIndex (hierarchical index)
arrays = [['A', 'A', 'B', 'B'], ['one', 'two', 'one', 'two']]
index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'SubCategory'))
df = pd.DataFrame(np.random.randint(1, 100, size=(4, 3)), index=index, columns=['Value1', 'Value2', 'Value3'])
print("MultiIndex DataFrame:")
display(df)

# Basic indexing and slicing operations
print("Indexing at Category 'A':")
display(df.loc['A'])

print("Slicing at Category 'B' and SubCategory 'two':")
display(df.loc[('B', 'two')])

MultiIndex DataFrame:

                      Value1  Value2  Value3
Category SubCategory
A        one              31      82      80
         two               3      40      71
B        one              38      54      80
         two              73      15      11

Indexing at Category 'A':

             Value1  Value2  Value3
SubCategory
one              31      82      80
two               3      40      71

Slicing at Category 'B' and SubCategory 'two':

Value1    73
Value2    15
Value3    11
Name: (B, two), dtype: int32

2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

In [22]:
# Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'
arrays = [
    ['A','A','A','B','B','B'],
    ['one','one','two','one','two','two']
]
index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'SubCategory'))
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 3)), index=index, columns=['Value1', 'Value2', 'Value3'])
print("MultiIndex DataFrame:")
display(df)
sum_values = df.groupby(['Category', 'SubCategory']).sum()
print("Sum of values:")
display(sum_values)

MultiIndex DataFrame:

                      Value1  Value2  Value3
Category SubCategory
A        one              42      71      25
         one              17      40      40
         two              87      84      47
B        one              58      16      98
         two              55      15      13
         two              74      37      10

Sum of values:

                      Value1  Value2  Value3
Category SubCategory
A        one              59     111      65
         two              87      84      47
B        one              58      16      98
         two             129      52      23

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.

In [34]:
df = pd.read_csv("data.csv")
display(df)
df.isnull().sum()
df.dropna(inplace=True)
df.isnull().sum()
pivot_table = df.pivot_table(values="Value",columns="Category",index="Date",aggfunc="sum")
display(pivot_table)

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

Category       A     B     C
Date
2023-01-01  28.0   NaN   NaN
2023-01-02   NaN  39.0   NaN
2023-01-03   NaN   NaN  32.0
2023-01-04   NaN   8.0   NaN
2023-01-05   NaN  26.0   NaN
2023-01-06   NaN  54.0   NaN
2023-01-07  16.0   NaN   NaN
2023-01-08   NaN   NaN  89.0
2023-01-09   NaN   NaN  37.0
2023-01-10  22.0   NaN   NaN
2023-01-11   NaN   7.0   NaN
2023-01-13  70.0   NaN   NaN
2023-01-14  69.0   NaN   NaN
2023-01-15  47.0   NaN   NaN
2023-01-17   NaN   NaN  93.0
2023-01-19  31.0   NaN   NaN
2023-01-20  59.0   NaN   NaN
2023-01-21   NaN   NaN  82.0
2023-01-22   NaN   NaN  37.0
2023-01-23   NaN  62.0   NaN
2023-01-24   NaN   NaN  92.0
2023-01-25  24.0   NaN   NaN
2023-01-26   NaN   NaN  95.0
2023-01-27   NaN   NaN  71.0
2023-01-28   NaN   NaN  56.0
2023-01-30   NaN   NaN  51.0
2023-01-31   NaN  50.0   NaN
2023-02-01  17.0   NaN   NaN
2023-02-02   NaN  63.0   NaN
2023-02-04   NaN   NaN  70.0
2023-02-06   NaN   NaN  36.0
2023-02-08   NaN   NaN  94.0
2023-02-09  62.0   NaN   NaN
2023-02-10   NaN  15.0   NaN
2023-02-11   NaN   NaN  97.0
2023-02-12  93.0   NaN   NaN
2023-02-13  43.0   NaN   NaN
2023-02-14  96.0   NaN   NaN
2023-02-15   NaN  99.0   NaN
2023-02-16   NaN   6.0   NaN
2023-02-17   NaN  69.0   NaN
2023-02-18   NaN   NaN  65.0
2023-02-19   NaN   NaN  11.0

2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

In [38]:
df = pd.DataFrame({'Year': np.random.choice([2020, 2021, 2022], size=12), 'Quarter': np.random.choice(['Q1', 'Q2', 'Q3', 'Q4'], size=12), 'Revenue': np.random.randint(1, 1000, size=12)})
print("Original DataFrame:")
display(df)
pivot_table = df.pivot_table(values="Revenue",columns="Quarter",index="Year",aggfunc="mean")
display(pivot_table)

Original DataFrame:

    Year Quarter  Revenue
0   2021      Q1      797
1   2020      Q4      731
2   2022      Q1      862
3   2021      Q3      497
4   2021      Q1      449
5   2022      Q1      501
6   2021      Q2      782
7   2021      Q1       35
8   2020      Q2      413
9   2021      Q3      304
10  2020      Q1       23
11  2021      Q2      286

Quarter     Q1     Q2     Q3     Q4
Year
2020      23.0  413.0    NaN  731.0
2021     427.0  534.0  400.5    NaN
2022     681.5    NaN    NaN    NaN

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.

In [42]:
df = pd.DataFrame(np.random.randint(10,101,size=(5,3)),columns=("A","B","C"))
print("Original df")
display(df)
print("Doubled df")
doubled_df = df.apply(lambda x:x*2)
display(doubled_df)

Original df

    A   B   C
0  50  56  93
1  11  81  68
2  95  66  16
3  39  18  13
4  45  45  15

Doubled df

     A    B    C
0  100  112  186
1   22  162  136
2  190  132   32
3   78   36   26
4   90   90   30

2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

In [47]:
df = pd.DataFrame(np.random.randint(1,101,size=(6,3)),columns=("A","B","C"))
display(df)
df["Sum"] = df.apply(lambda row: row.sum(), axis=1)
display(df)

    A   B   C
0  62  62  58
1  33  26  48
2  80  61  81
3   8   6  84
4  51  91   1
5  36  65  64

    A   B   C  Sum
0  62  62  58  182
1  33  26  48  107
2  80  61  81  222
3   8   6  84   98
4  51  91   1  143
5  36  65  64  165

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.

In [50]:
df = pd.Series(["Apple","Mango","Orange","Grapes","Banana"])
display(df)
display(df.str.upper())

0     Apple
1     Mango
2    Orange
3    Grapes
4    Banana
dtype: object

0     APPLE
1     MANGO
2    ORANGE
3    GRAPES
4    BANANA
dtype: object

2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [53]:
df = pd.Series(["Apple","Mango","Orange","Grapes","Banana"])
display(df)
display(df.str[0:3])

0     Apple
1     Mango
2    Orange
3    Grapes
4    Banana
dtype: object

0    App
1    Man
2    Ora
3    Gra
4    Ban
dtype: object

---

# 🎉 Assignment Summary

Successfully completed all **10 Pandas Assignments** covering the fundamentals and intermediate concepts of the library.

## ✅ Skills Acquired

- Creating and manipulating DataFrames
- Indexing and slicing data
- Performing arithmetic operations
- Handling missing values
- Grouping and aggregation
- Merging and concatenating datasets
- Working with time series data
- Creating and using MultiIndex DataFrames
- Building Pivot Tables
- Applying custom functions with `apply()` and `lambda`
- Processing string/text data

---

## 🚀 What's Next?

The next step in my Data Analytics roadmap is:

- 📊 Matplotlib
- 🎨 Seaborn
- 📈 Exploratory Data Analysis (EDA)
- ⚙️ Feature Engineering
- 📐 Statistics
- 🤖 Machine Learning

---

## 💡 Key Takeaway

> "Pandas isn't just a library for manipulating tables—it's the foundation of real-world data analysis. Mastering it enables efficient cleaning, transformation, exploration, and preparation of data for analytics and machine learning."

---

### ⭐ Thank you for visiting this notebook!

If you found this repository helpful, consider giving it a ⭐ on GitHub.