In [3]:
import pandas as pd

In [4]:
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [16]:
## Creating DF from Dict list 

data={
    'Name':['Govinda','John','Jack'],
    'Age':[23,30,45],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0  Govinda   23  Bangalore
1     John   30   New York
2     Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

In [17]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Govinda','Age':23,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'Jack','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0  Govinda   23  Bangalore
1     John   34  Bangalore
2    Bappy   32  Bangalore
3     Jack   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [9]:
df = pd.read_csv("data.csv")

In [10]:
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [11]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [12]:
### Accessing Data From Dataframe
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [13]:
df['Product']

0     Product1
1     Product3
2     Product2
3     Product1
4     Product3
5     Product3
6     Product1
7     Product1
8     Product3
9     Product2
10    Product1
11    Product2
12    Product3
13    Product1
14    Product2
15    Product1
16    Product2
17    Product1
18    Product2
19    Product1
20    Product3
21    Product2
22    Product3
23    Product2
24    Product2
25    Product1
26    Product2
27    Product2
28    Product3
29    Product2
30    Product3
31    Product2
32    Product3
33    Product3
34    Product3
35    Product2
36    Product3
37    Product1
38    Product1
39    Product1
40    Product1
41    Product1
42    Product3
43    Product3
44    Product3
45    Product2
46    Product1
47    Product3
48    Product3
49    Product3
Name: Product, dtype: object

In [14]:
df.loc[0]

Date        2023-01-01
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object

In [15]:
df.iloc[0]

Date        2023-01-01
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object

In [18]:
data=[
    {'Name':'Govinda','Age':23,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'Jack','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0  Govinda   23  Bangalore
1     John   34  Bangalore
2    Bappy   32  Bangalore
3     Jack   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [19]:
df

      Name  Age       City
0  Govinda   23  Bangalore
1     John   34  Bangalore
2    Bappy   32  Bangalore
3     Jack   32  Bangalore

In [21]:
## Accessing a specified element
df.at[2,'Age']

np.int64(32)

In [22]:
df.at[2,'Name']

'Bappy'

In [23]:
## Accessing a specified element using iat
df.iat[2,2]

'Bangalore'

In [25]:
## Adding a column
df['Salary']=[50000,60000,70000,45000]
df

      Name  Age       City  Salary
0  Govinda   23  Bangalore   50000
1     John   34  Bangalore   60000
2    Bappy   32  Bangalore   70000
3     Jack   32  Bangalore   45000

In [26]:
df

      Name  Age       City  Salary
0  Govinda   23  Bangalore   50000
1     John   34  Bangalore   60000
2    Bappy   32  Bangalore   70000
3     Jack   32  Bangalore   45000

In [27]:
## Remove a column
df.drop('Salary',axis=1,inplace=True)

In [28]:
df

      Name  Age       City
0  Govinda   23  Bangalore
1     John   34  Bangalore
2    Bappy   32  Bangalore
3     Jack   32  Bangalore

In [29]:
## Add age to the column
df['Age']=df['Age']+1
df

      Name  Age       City
0  Govinda   24  Bangalore
1     John   35  Bangalore
2    Bappy   33  Bangalore
3     Jack   33  Bangalore

In [30]:
df=pd.read_csv('data.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [31]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

Data types:
 Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [32]:
# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Statistical summary:
            Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [33]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000