PERFECT. 😈

Now we're entering the **Data Analyst mode**.

I'm not going to ask you syntax anymore. I'm going to ask you the kind of questions an analyst gets after receiving a CSV.

Your dataset has:

```text
Date
Category
Value
Product
Sales
Region
```

---


---



# 🔵 Level 3 (Visualization)

No Seaborn.

Only Matplotlib + Pandas.

---

### Q11

Create a bar chart showing

> Total Sales by Region

---

### Q12

Create a pie chart showing

> Sales contribution of each Category

---

### Q13

Create a histogram of

```text
Sales
```

Questions to answer:

* Is the distribution symmetric?
* Are there any extreme values?

---

### Q14

Create a scatter plot

```text
Value
vs
Sales
```

Question:

> Does higher Value generally mean higher Sales?

---

### Q15

Create a line chart showing

Total Sales over Date.

(Hint: You'll need `groupby()`.)

---

# 🔴 Level 4 (Interview Style)

### Q16

Using a Pivot Table,

Create

```text
Rows -> Region

Columns -> Category

Values -> Sales

Aggregation -> Sum
```

---

### Q17

Find

The average sales in each region using `groupby()`.

---

### Q18

Find

The product that appears the most.

(Hint: Don't use `groupby()`.)

---

### Q19

Which day recorded the highest sales?

---

### Q20 ⭐ Challenge

Create **one dashboard** (using `plt.subplot()`) containing:

* 📊 Bar Chart → Sales by Region
* 🥧 Pie Chart → Category Distribution
* 📈 Line Plot → Sales over Time
* 📉 Histogram → Sales Distribution

---

# 🎯 Bonus (Real Interview)

These are the exact type of business questions you may be asked:

1. Which region performs best?
2. Which product contributes the highest revenue?
3. Which category should the company invest in?
4. Which day had unusually high sales?
5. Is there any relationship between `Value` and `Sales`?
6. If you were the manager, what are **three business insights** you would present based on this dataset?

---

## 🏆 My Challenge for You

Don't send me one answer at a time like before.

Solve **Q1–Q20** in your notebook as if this were a company assignment. When you're done, send me the notebook (or screenshots), and I'll review it like a technical interviewer. I'll point out:

* better Pandas alternatives,
* cleaner plotting practices,
* interview tips,
* and how to make your code more production-ready.

If you can comfortably solve these 20 questions, you'll be well prepared for the kind of data manipulation and visualization expected in many entry-level Data Analyst interviews.

# 🟢 Level 1 (Warm-up)

### Q1

Display the first 10 rows.

---

### Q2

Show:

* shape
* info
* describe

---

### Q3

How many unique products are there?

(Hint: don't use loops.)

---

### Q4

How many transactions happened in each region?

Expected output:

```text
Region
East
North
South
West
```

---

### Q5

Find the total sales of each category.
---

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#1
df = pd.read_csv("data.csv")
display(df.head(10))

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
5  2023-01-06        B   54.0  Product3  192.0   West
6  2023-01-07        A   16.0  Product1  936.0   East
7  2023-01-08        C   89.0  Product1  488.0   West
8  2023-01-09        C   37.0  Product3  772.0   West
9  2023-01-10        A   22.0  Product2  834.0   West

In [ ]:
#2
print(df.shape)
display(df.info())
display(df.describe())

(50, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      50 non-null     object
 1   Category  50 non-null     object
 2   Value     47 non-null     float64
 3   Product   50 non-null     object
 4   Sales     46 non-null     float64
 5   Region    50 non-null     object
dtypes: float64(2), object(4)
memory usage: 2.5+ KB

None

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [8]:
#3
df["Product"].unique()

array(['Product1', 'Product3', 'Product2'], dtype=object)

In [ ]:
#4
df.groupby("Region")["Sales"].count()

Region
East     12
North    10
South     8
West     16
Name: Sales, dtype: int64

In [ ]:
#5
df.groupby("Category")["Sales"].sum()

Category
A    8527.0
B    7425.0
C    9676.0
Name: Sales, dtype: float64

# 🟡 Level 2 (Intermediate)

### Q6

Which product generated the highest total sales?

---

### Q7

Which region generated the highest revenue?

---

### Q8

Find the average sales of every product.

---

### Q9

Create a new column called

```text
Discounted_Sales
```

Assume every product gets a **10% discount**.

---

### Q10

Find the top 5 highest sales records.

---

In [ ]:
#6
highest_sold_product = df.groupby("Product")["Sales"].sum().reset_index()
highest_sold_product.nlargest(1,"Sales")

    Product   Sales
2  Product3  9631.0

In [26]:
#7
df.groupby("Region")["Sales"] .sum() .reset_index() .nlargest(1, "Sales")

  Region   Sales
3   West  7445.0

In [27]:
#8
df.groupby("Product")["Sales"].mean().reset_index()

    Product       Sales
0  Product1  574.866667
1  Product2  567.230769
2  Product3  535.055556

In [ ]:
#9
print("Before discount")
display(df.head(10))
df["Sales"]=df["Sales"]*0.9
print("After discount")
display(df.head(10))

Before discount

         Date Category  Value   Product  Sales Region  discount
0  2023-01-01        A   28.0  Product1  754.0   East     678.6
1  2023-01-02        B   39.0  Product3  110.0  North      99.0
2  2023-01-03        C   32.0  Product2  398.0   East     358.2
3  2023-01-04        B    8.0  Product1  522.0   East     469.8
4  2023-01-05        B   26.0  Product3  869.0  North     782.1
5  2023-01-06        B   54.0  Product3  192.0   West     172.8
6  2023-01-07        A   16.0  Product1  936.0   East     842.4
7  2023-01-08        C   89.0  Product1  488.0   West     439.2
8  2023-01-09        C   37.0  Product3  772.0   West     694.8
9  2023-01-10        A   22.0  Product2  834.0   West     750.6

After discount

         Date Category  Value   Product  Sales Region  discount
0  2023-01-01        A   28.0  Product1  678.6   East     678.6
1  2023-01-02        B   39.0  Product3   99.0  North      99.0
2  2023-01-03        C   32.0  Product2  358.2   East     358.2
3  2023-01-04        B    8.0  Product1  469.8   East     469.8
4  2023-01-05        B   26.0  Product3  782.1  North     782.1
5  2023-01-06        B   54.0  Product3  172.8   West     172.8
6  2023-01-07        A   16.0  Product1  842.4   East     842.4
7  2023-01-08        C   89.0  Product1  439.2   West     439.2
8  2023-01-09        C   37.0  Product3  694.8   West     694.8
9  2023-01-10        A   22.0  Product2  750.6   West     750.6

In [37]:
df.sort_values("Sales",ascending=False).head(5)

          Date Category  Value   Product  Sales Region  discount
21  2023-01-22        C   37.0  Product2  892.8  South     892.8
43  2023-02-13        A   43.0  Product3  854.1   East     854.1
22  2023-01-23        B   62.0  Product3  847.8  North     847.8
46  2023-02-16        B    6.0  Product1  844.2  South     844.2
6   2023-01-07        A   16.0  Product1  842.4   East     842.4